kind: pipeline
name: default

steps:
- name: Build a site
  image: squidfunk/mkdocs-material:latest
  pull: if-not-exists
  commands:
  - pip install -U -r ./requirements.txt
  - mkdocs build

- name: Publish docker image
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PWD
    tags:
      - latest
    repo: spetriuk/dev-lab-docs

- name: Deploy to dev-server
  image: robkaandorp/drone-portainer
  settings:
    portainer_url: http://portainer.tinker.my
    portainer_username:
      from_secret: PORTAINER_USERNAME
    portainer_password:
      from_secret: PORTAINER_PASSWORD
    endpoint: server1
    registry: docker.io
    image: spetriuk/dev-lab-docs
    image_tag: latest
    stack_name: docs
    standalone: false

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock