kind: pipeline
name: default

steps:
- name: Build a site
  image: squidfunk/mkdocs-material:latest
  pull: if-not-exists
  commands:
  - pip install -U -r ./requirements.txt
  - mkdocs build
  when:
    event: push
    branch: main

- name: publish-image
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PWD
    tags:
      - latest
    repo: spetriuk/dev-lab-docs
  when:
    event: push
    branch: main

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock